// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pws.Server.Infrastructure;

namespace pws.server.Migrations
{
    [DbContext(typeof(WorkManagement))]
    [Migration("20200908151127_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("pws.Shared.Domain.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkerName");

                    b.ToTable("WorkItem");
                });

            modelBuilder.Entity("pws.Shared.Domain.Worker", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("pws.Shared.Domain.WorkItem", b =>
                {
                    b.HasOne("pws.Shared.Domain.Worker", null)
                        .WithMany("WorkItems")
                        .HasForeignKey("WorkerName");
                });
#pragma warning restore 612, 618
        }
    }
}
